# Generated by Django 4.1.6 on 2023-02-06 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_collaborator_note_color_note_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='collaborator',
        ),
        migrations.RemoveField(
            model_name='note',
            name='label',
        ),
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
        migrations.DeleteModel(
            name='Labels',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
