# Generated by Django 4.1.6 on 2023-02-16 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Note'},
        ),
    ]
