# Generated by Django 4.1.6 on 2023-02-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_note_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labels',
            old_name='name',
            new_name='label_name',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='content',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
