# Generated by Django 4.1.6 on 2023-02-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_rename_name_labels_label_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labels',
            name='label_name',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
