# Generated by Django 4.1.7 on 2023-02-26 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userlog_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlog',
            old_name='urls',
            new_name='url',
        ),
    ]
