# Generated by Django 4.1.7 on 2023-02-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_urls_userlog_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
